name: CI-instagram-app

on:
  push:
    branches: [dev, main]
    # Only consider those paths to trigger the action
    paths:
      - 'apps/instagram-app/**'
      - 'packages/**'
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/**'

  pull_request:
    types: [opened, synchronize, reopened]
    # Only consider those paths to trigger the action
    paths:
      - 'apps/instagram-app/**'
      - 'packages/**'
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/**'
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/instagram-app
    strategy:
      matrix:
        node-version: [18.x]
    env:
      TURBO_API: 'http://127.0.0.1:9080'
      TURBO_TEAM: 'monorepo-clone-template'
      TURBO_TOKEN: 'local_server_turbo_relaxed_token'

    steps:
      - uses: actions/checkout@v4

      - name: âš™ï¸ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: â© TurboRepo local server
      #   uses: felixmosh/turborepo-gh-artifacts@v2
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     server-token: ${{ env.TURBO_TOKEN }}

      - name: ğŸ“¥ Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: â™»ï¸ Restore instagram-app related caches
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/apps/instagram-app/.next/cache
            ${{ github.workspace }}/.cache
            ${{ github.workspace }}/**/tsconfig.tsbuildinfo
          key: instagram-app-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: ğŸ•µï¸ Typecheck
        run: yarn --top-level run turbo typecheck

      - name: ğŸ”¬ Linter
        run: yarn --top-level run turbo lint
        env:
          TIMING: 1

      # - name: ğŸ§ª Unit tests
      #   run: yarn --top-level run turbo test-unit

      # build ì•ˆí•´!
      # - name: ğŸ— Build web-app
      #   run: yarn --top-level run turbo build
      #   env:
      #     NEXT_BUILD_ENV_ESLINT: false
      #     NEXT_BUILD_ENV_TYPECHECK: false
      #     NEXT_BUILD_ENV_SOURCEMAPS: false

      # - name: ğŸ›Ÿ Check ecmascript checks for build files
      #   run: yarn check-dist
